-- AlterTable
ALTER TABLE "Cart" ALTER COLUMN "originalPrice" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "shippingPrice" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalPrice" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Currency" ALTER COLUMN "parallel_sale" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "parallel_purchase" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "official_rate" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Feedback" ALTER COLUMN "rating" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "originalPrice" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalPrice" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "shippingPrice" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Wishlist" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;